apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstoneproject
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate          
  template:
    metadata:
      labels:
        app: capstoneproject
    spec:
      containers:
      - name: capstoneproject
        image: preyan0901/capstoneproject:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        